- name: disable ssh empty password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin*|^##PermitRootLogin*'
    line: "PermitRootLogin no"
  become: yes
  
- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: yes
