- name: disable ssh empty password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication*|^PubkeyAuthentication*'
    line: "PubkeyAuthentication yes"
  become: yes

- name: disable ssh empty password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication*|^PasswordAuthentication*'
    line: "PasswordAuthentication no"
  become: yes

- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: yes
