- name: Limit user'ssh access from ip
  lineinfile:
    path: /etc/ssh/sshd_config
    line: AllowUsers test1@192.168.2.1
  become: yes
  
- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: yes 

